const IMAGE_FIELDS = `asset->, alt, caption, hotspot, crop`;

export const ALL_HERO_SLIDES_QUERY = `*[_type == "heroSlide"] | order(order asc) { _id, title, subtitle, backgroundImage { ${IMAGE_FIELDS} }, ctaLabel, ctaLink, ctaType, order }`;
export const ALL_STATS_QUERY = `*[_type == "stat"] | order(order asc) { _id, label, value, suffix, prefix, icon, order }`;
export const ALL_PARTNERS_QUERY = `*[_type == "partner"] | order(order asc) { _id, name, abbreviation, logo { ${IMAGE_FIELDS} }, url, order }`;
export const ALL_COURSES_QUERY = `*[_type == "course"] | order(order asc) { _id, title, "slug": slug.current, coverImage { ${IMAGE_FIELDS} }, category, description, professor, topics[] { title, description, classes }, pricePEN, priceUSD, totalClasses, totalHours, level, featured, order, courseType }`;
export const FEATURED_COURSES_QUERY = `*[_type == "course" && featured == true] | order(order asc) { _id, title, "slug": slug.current, coverImage { ${IMAGE_FIELDS} }, category, description, professor, pricePEN, priceUSD, totalClasses, totalHours, level, featured, order, courseType }[0..6]`;
export const ALL_TESTIMONIALS_QUERY = `*[_type == "testimonial"] | order(order asc) { _id, authorName, authorRole, quote, photo { ${IMAGE_FIELDS} }, rating, featured, order }`;
export const FEATURED_TESTIMONIALS_QUERY = `*[_type == "testimonial" && featured == true] | order(order asc) { _id, authorName, authorRole, quote, photo { ${IMAGE_FIELDS} }, rating, featured, order }[0..6]`;
export const ALL_TEAM_QUERY = `*[_type == "teamMember"] | order(order asc) { _id, name, role, photo { ${IMAGE_FIELDS} }, bio, email, linkedinUrl, order }`;
export const SITE_SETTINGS_QUERY = `*[_type == "siteSettings"][0] { _id, companyName, slogan, tagline, logo { ${IMAGE_FIELDS} }, logoWhite { ${IMAGE_FIELDS} }, ogImage { ${IMAGE_FIELDS} }, heroVideo { asset-> { _id, url, mimeType, size } }, heroVideoUrl, heroVideoOverlay, whatsapp, whatsappMessage, whatsappVisible, phone, email, tiktokUrl, instagramUrl, youtubeUrl, facebookUrl, seoTitle, seoDescription }`;
export const PAGE_CONTENT_QUERY = (pageId: string) => `*[_type == "pageContent" && pageId == "${pageId}"][0] { _id, pageId, pageTitle, heroTitle, heroSubtitle, heroImage { ${IMAGE_FIELDS} }, ctaLabel, ctaLink, bodyContent[], seoTitle, seoDescription }`;
export const COURSE_BY_SLUG_QUERY = (slug: string) => `*[_type == "course" && slug.current == "${slug}"][0] { _id, title, "slug": slug.current, coverImage { ${IMAGE_FIELDS} }, category, description, professor, topics[] { title, description, classes }, pricePEN, priceUSD, totalClasses, totalHours, level, featured, order, courseType, courseVideo { asset-> { _id, url, mimeType, size } }, videoUrl, classVideos[] { title, description, video { asset-> { _id, url, mimeType, size } }, videoUrl, sharedVideo-> { _id, title, videoFile { asset-> { _id, url, mimeType, size } }, videoUrl, webmUrl, duration }, duration, topic, isFree, order }, topicMaterials[] { title, topic, file { asset-> { _id, url, mimeType, size } }, order } }`;
export const ALL_VIDEO_LIBRARY_QUERY = `*[_type == "videoLibrary"] | order(title asc) { _id, title, description, videoFile { asset-> { _id, url, mimeType, size } }, videoUrl, webmUrl, duration, thumbnail { asset->, alt, caption, hotspot, crop }, tags }`;
export const VIDEO_LIBRARY_BY_ID_QUERY = (id: string) => `*[_type == "videoLibrary" && _id == "${id}"][0] { _id, title, videoFile { asset-> { _id, url, mimeType, size } }, videoUrl, webmUrl, duration }`;

export const THEME_SETTINGS_QUERY = `*[_type == "themeSettings"][0] { _id, preset, colorsSection { primaryColor, primaryHoverColor, headingColor, textColor, linkColor, buttonColor, buttonHoverColor, buttonTextColor, secondaryColor } }`;